---
- name: Configure as Logstash server
  hosts: all
  remote_user: "{{ pi_remote_user }}"
  sudo: yes
  roles:
  - role: geerlingguy.java
  - role: elasticsearch
  - role: logstash
  - role: filebeat
  - role: logstash_config
  vars_files:
  - group_vars/shared
