---
- name: Initial setup after ssh configuretion  Setup servers
  hosts: logstash
  remote_user: "{{ pi_remote_user }}"
  become: yes
  roles:
  - role: common
  - role: unzip
  - role: linux_harden
  vars_files:
    - group_vars/shared
