# -*- mode: ruby -*-
# vi: set ft=ruby :
role = File.basename(File.expand_path(File.dirname(__FILE__)))

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu/xenial64"
  config.vm.synced_folder '.', '/vagrant', disabled:true 
  config.vm.hostname = "ansible-iac-linux-harden-2"

  config.vm.provision "shell", inline: <<-SHELL
    test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)
  SHELL


  config.vm.provision :ansible do |ansible|
       ansible.playbook = "test/vagrant.yml"
       ansible.raw_arguments = ['--syntax-check']
  end

  config.vm.provision :ansible do |ansible|
       ansible.playbook = "test/vagrant.yml"
       ansible.become= true
  end

  ## do testing playbooks here
  #config.vm.provision :ansible do |ansible|
  #     ansible.playbook = "test/test.yml"
  #     #ansible.sudo = true
  #     ansible.raw_arguments = ['--syntax-check']
  #     ansible.raw_arguments = ['-e', 'role_name=aic-nginx']
  #     ansible.raw_arguments = ['-e',  'hosts_group=hosts_group']
  #end

end
