---
- name: Create "{{ rax_server_name }}" server(s)
  local_action:
    module: rax
    name: "{{ rax_server_name }}"
    flavor: "{{ rax_os_flavour }}"
    image: "{{ rax_image_name }}"
    disk_config: "{{ rax_disk_config }}"
    networks: "{{ rax_network_names }}"
    region: "{{ rax_dc_region }}"
    keypair: "{{ rax_keypair }}"
    state: present
    count: "{{ rax_count }}"
    exact_count: yes
    group: "{{ rax_server_group }}"
    wait: yes
    wait_timeout: 1200
  register: rax

- name: Add servers to in memory groups
  local_action:
    module: add_host
    hostname: "{{ item.name }}"
    ansible_host: "{{ item.rax_accessipv4 }}"
    rax_id: "{{ item.rax_id }}"
    groups: "{{ rax_server_group }}"
  with_items: "{{ rax.success }}"
  when: rax.action == 'create'
