---
- name: Disallow password authentication
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PasswordAuthentication"
              line="PasswordAuthentication no"
              state=present
  notify: Restart ssh

- name: Disallow root SSH access
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PermitRootLogin"
              line="PermitRootLogin no"
              state=present
  notify: Restart ssh

- name: Allow rackconnect user to use password-based authentication
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      Match User rackconnect
      PasswordAuthentication yes

- name: Install aptitude
  become: yes
  apt:
    state: installed
    pkg: aptitude
  tags: publishinteractive-harden

- name: Update apt caches
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags: publishinteractive-harden

- name: Upgrade apt to the latest packages
  become: yes
  apt:
    upgrade: safe
  tags: publishinteractive-harden

- name: Install unattended-upgrades
  become: yes
  apt:
    state: installed
    pkg: unattended-upgrades
  tags: publishinteractive-harden

- name: "Install Fail2ban {{ pi_fail2ban_version }}"
  become: yes
  apt:
    state: installed
    pkg: "fail2ban={{ pi_fail2ban_version }}"
  tags: publishinteractive-harden

- name: "Install Logwatch {{ pi_logwatch_version }}"
  become: yes
  apt:
    state: installed
    pkg: "logwatch={{ pi_logwatch_version }}"
  tags: publishinteractive-harden

- name: Adjust APT update intervals
  become: yes
  copy:
    src: "assets/unattended-upgrades/apt_periodic"
    dest: "/etc/apt/apt.conf.d/10periodic"
  tags: publishinteractive-harden

- name: Set up Postfix to relay mail
  become: yes
  debconf: name=postfix
           question='{{ item.question }}'
           value='{{ item.value }}'
           vtype='{{ item.vtype }}'
  with_items:
    - { question: 'postfix/mailname', value: '{{ ansible_fqdn }}', vtype: 'string' }
    - { question: 'postfix/main_mailer_type', value: 'Internet Site', vtype: 'string' }
  tags: publishinteractive-harden

- name: Email log summary daily
  become: yes
  lineinfile: dest=/etc/cron.daily/00logwatch
              regexp="^/usr/sbin/logwatch"
              line="/usr/sbin/logwatch --output mail --mailto {{ pi_ops_notification_email_noncritical }} --detail high"
              state=present create=yes
  tags: publishinteractive-harden
