---
galaxy_info:
  author: "Publishing Interactive"
  license: BSD
  min_ansible_version: 2.2
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: opensuse
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: FreeBSD
      versions:
        - 10.0
        - 10.1
        - 10.2
        - 10.3
        - 11.0
  galaxy_tags:
    - tools 
allow_duplicates: yes
dependencies: []
