#!/bin/bash
# Script should be run from the root directory of the repository

#Add Github SSH key to SSH agent for Galxy pull
#chmod 0700 assets/secrets/ssh/id_rsa_github
#ssh-add assets/secrets/ssh/id_rsa_github

ansible-playbook  local.yml

#Ansible galaxy command to download all the dependencie#
ansible-galaxy install -p roles -r dependency_install.yml

#Set location of RAX_CREDS_FILE as enviornment variable
#export RAX_CREDS_FILE=$(readlink --canonicalize assets/secrets/rax_creds)

#Rax module to create the required Logstash server
ansible-playbook init.yml

#Main playbook to do setup and run  logstash
ansible-playbook -i inventories/rax.py main.yml
